/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.una.tramites.loaders;

/**
 *
 * @author LordLalo
 */
public enum Permisos {
    USUARIO_CREAR("USU1"),
    USUARIO_MODIFICAR("USU2"),
    USUARIO_INACTIVAR("USU3"),
    USUARIO_CONSULTAR("USU4"),
    USUARIO_CONSULTAR_CEDULA("USU5"),
    USUARIO_CONSULTAR_NOMBRE("US6"),
    USUARIO_CONSULTAR_TODO("USU7"),
    USUARIO_ELIMINAR("USU8"),
    USUARIO_ELIMINAR_TODO("USU9"),
    DEPARTAMENTO_CREAR("DEP1"),
    DEPARTAMENTO_MODIFICAR("DEP2"),
    DEPARTAMENTO_INACTIVAR("DEP3"),
    DEPARTAMENTO_CONSULTAR("DEP4"),
    DEPARTAMENTO_CONSULTAR_ESTADO("DEP5"),
    DEPARTAMENTO_CONSULTAR_DESCRIPCION("DEP6"),
    DEPARTAMENTO_CONSULTAR_TODO("DEP7"),
    DEPARTAMENTO_ELIMINAR("DEP8"),
    DEPARTAMENTO_ELIMINAR_TODO("DEP9"),
    TRAMITE_REGISTRAR("TRA1"),
    TRAMITE_MODIFICAR("TRA2"),
    TRAMITE_INACTIVAR("TRA3"),
    TRAMITE_FINALIZAR("TRA4"),
    TRAMITE_CONSULTAR("TRA5"),
    TRAMITE_CONSULTAR_TODO("TRA6"),
    TRAMITE_REGISTRAR_("TRA7"),
    TRAMITE_ELIMINAR("TRA8"),
    TRAMITE_ELIMINAR_TODO("TRA9"),
    TRAMITE_DISEÑAR("TRD1"),
    TRAMITE_TIPO_CREAR("TRT1"),
    TRAMITE_TIPO_MODIFICAR("TRT2"),
    TRAMITE_TIPO_CONSULTAR("TRT3"),
    TRAMITE_TIPO_CONSULTAR_ESTADO("TRT4"),
    TRAMITE_TIPO_CONSULTAR_DESCRIPCION("TRT5"),
    TRAMITE_TIPO_CONSULTAR_TODO("TRT6"),
    TRAMITE_ESTADO_CONSULTAR_TODO("TRE1"),
    TRAMITE_ESTADO_CONSULTAR("TRE2"),
    TRAMITE_ESTADO_CREAR("TRE2"),
    TRAMITE_ESTADO_MODIFICAR("TRE3"),
    TRAMITE_ESTADO_ELIMINAR("TRE4"),
    TRAMITE_ESTADO_ELIMINAR_TODO("TRE5"),
    TRAMITE_CAMBIO_ESTADO_CONSULTAR_TODO("TCA1"),
    TRAMITE_CAMBIO_ESTADO_CONSULTAR("TCA2"),
    TRAMITE_CAMBIO_ESTADO_CREAR("TCA2"),
    TRAMITE_CAMBIO_ESTADO_MODIFICAR("TCA3"),
    TRAMITE_CAMBIO_ESTADO_ELIMINAR("TCA4"),
    TRAMITE_CAMBIO_ESTADO_ELIMINAR_TODO("TCA5"),
    TRANSACCION_CONSULTAR("TRU1"),
    TRANSACCION_CREAR("TRU2"),
    NOTA_CONSULTAR_TODO("NOT1"),
    NOTA_CONSULTAR("NOT2"),
    NOTA_CREAR("NOT2"),
    NOTA_MODIFICAR("NOT3"),
    NOTA_ELIMINAR("NOT4"),
    NOTA_ELIMINAR_TODO("NOT5"),
    ARCHIVO_RELACIONADO_CREAR("ARC1"),
    ARCHIVO_RELACIONADO_MODIFICAR("ARC2"),
    ARCHIVO_RELACIONADO_CONSULTAR("ARC3"),
    ARCHIVO_RELACIONADO_CONSULTAR_TODO("ARC4"),
    ARCHIVO_RELACIONADO_ELIMINAR("ARC5"),
    ARCHIVO_RELACIONADO_ELIMINAR_TODO("ARC6"),
    CLIENTE_CREAR("CLI1"),
    CLIENTE_MODIFICAR("CLI2"),
    CLIENTE_INACTIVAR("CLI3"),
    CLIENTE_CONSULTAR("CLI4"),
    CLIENTE_CONSULTAR_NOMBRE_APROXIMADO("CLI5"),
    CLIENTE_CONSULTAR_CEDULA_APROXIMADA("CLI6"),
    CLIENTE_CONSULTAR_TODO("CLI7"),
    CLIENTE_ELIMINAR("CLI8"),
    CLIENTE_ELIMINAR_TODO("CLI9"),
    PARAMETRO_GENERAL_CREAR("PAR1"),
    PARAMETRO_GENERAL_CONSULTAR("PAR2"),
    PARAMETRO_GENERAL_CONSULTAR_TODO("PAR53"),
    PARAMETRO_GENERAL_ELIMINAR("PAR4"),
    PARAMETRO_GENERAL_ELIMINAR_TODO("PAR5"),
    REQUISITO_CREAR("REQ1"),
    REQUISITO_CONSULTAR("REQ2"),
    REQUISITO_CONSULTAR_TODO("REQ3"),
    REQUISITO_ELIMINAR("REQ4"),
    REQUISITO_ELIMINAR_TODO("REQ5"),
    REQUISITO_PRESENTADO_CONSULTAR("REP1"),
    REQUISITO_PRESENTADO_CONSULTAR_TODO("REP2"),
    REQUISITO_PRESENTADO_ELIMINAR("REP3"),
    REQUISITO_PRESENTADO_ELIMINAR_TODO("REP4"),
    VARIACION_CREAR("VAR1"),
    VARIACION_MODIFICAR("VAR2"),
    VARIACION_CONSULTAR("VAR3"),
    USUARIO_CONSULTAR_GRUPO("VAR4"),
    USUARIO_CONSULTAR_DESCRIPCION("VAR5"),
    VARIACION_CONSULTAR_TODO("VAR6"),
    VARIACION_ELIMINAR("VAR7"),
    VARIACION_ELIMINAR_TODO("VAR8");
    private String codigo;

    Permisos(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigo() {
        return codigo;
    }
}
